// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fenggwsx/filego/base/conf"
	"github.com/fenggwsx/filego/base/flags"
	"github.com/fenggwsx/filego/base/log"
	"github.com/fenggwsx/filego/base/server"
	"github.com/fenggwsx/filego/middleware"
)

// Injectors from wire.go:

func initApp() (*App, error) {
	flagSet := flags.NewFlagSet()
	config, err := conf.NewConfig(flagSet)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(config)
	if err != nil {
		return nil, err
	}
	loggerMiddleware := middleware.NewLoggerMiddleware(logger)
	recoveryMiddleware := middleware.NewRecoveryMiddleware(logger)
	httpServer := server.NewHttpServer(config, logger, loggerMiddleware, recoveryMiddleware)
	app := newApp(httpServer)
	return app, nil
}
